module.exports = {
  Romance: [
    'night_club',
    'restaurant',
    'jewelry_store',
    'museum',
    'art_gallery',
    'bar',
    'cafe',
    'aquarium',
  ],
  Thrill: [
    'amusement_park',
    'casino',
  ],
  Relaxation: [
    'spa',
    'beauty_salon',
    'hair_care',
    'park',
    'aquarium',
    'art_gallery',
    'museum',
  ],
  Food: [
    'restaurant',
    'cafe',
    'bakery',
  ],
  Family: [
    'amusement_park',
    'zoo',
    'aquarium',
    'art_gallery',
    'museum',
    'stadium',
    'church',
    'hindu_temple',
    'mosque',
    'synagogue',
  ],
  Outdoor: [
    'park',
    'campground',
    'zoo',
    'amusement_park',
    'stadium',
  ],
  Culture: [
    'museum',
    'art_gallery',
    'church',
    'aquarium',
    'stadium',
    'university',
    'hindu_temple',
    'mosque',
    'synagogue',
  ],
  Nightlife: [
    'bar',
    'night_club',
    'casino',
    'liquor_store',
  ],
  Shopping: [
    'shopping_mall',
    'department_store',
    'clothing_store',
    'jewelry_store',
    'shoe_store',
  ],
};
