module.exports = {
  ROMANCE: [
    'night_club',
    'restaurant',
    'jewelry_store',
    'museum',
    'art_gallery',
    'bar',
    'cafe',
    'aquarium',
  ],
  THRILL: [
    'amusement_park',
    'casino',
  ],
  RELAXATION: [
    'spa',
    'beauty_salon',
    'hair_care',
    'park',
    'aquarium',
    'art_gallery',
    'museum',
  ],
  FOODIE: [
    'restaurant',
    'cafe',
    'bakery',
  ],
  FAMILY: [
    'amusement_park',
    'zoo',
    'aquarium',
    'art_gallery',
    'museum',
    'stadium',
    'church',
    'hindu_temple',
    'mosque',
    'synagogue',
  ],
  OUTDOOR: [
    'park',
    'campground',
    'zoo',
    'amusement_park',
    'stadium',
  ],
  CULTURE_LANDMARKS: [
    'museum',
    'art_gallery',
    'aquarium',
    'stadium',
    'university',
    'church',
    'hindu_temple',
    'mosque',
    'synagogue',
  ],
  NIGHTLIFE: [
    'bar',
    'night_club',
    'casino',
    'liquor_store',
  ],
  SHOPPING: [
    'shopping_mall',
    'department_store',
    'clothing_store',
    'jewelry_store',
    'shoe_store',
  ],
};
